---
title: "Test Cases"
author: "William Denney"
date: "October 21, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

For each of the parameters, at least one test case will be given below.  The test cases are intended to be structured so that they test the underlying calculation in all reasonable scenarios including with a variety of algorithm choices.  The test cases are also structured so that they are easily usable by any software package with standardized naming of the concentration-time datasets, the algorithm selections, and the results.

All inputs and outputs are structured to be as simple as possible while being similar to CDISC SDTM standards.  The simplicity is used to enable as many software packages to test against the tests without requiring implementation or understanding of the full CDISC SDTM standard.

The examples along with the current version of this document can be obtained at the [NCA Consortium GitHub Page](https://github.com/NCAConsortium).

# Examples

(Examples including concentration-time data and calculation of all relevant parameters are planned here.)