---
title: "Input and Output Data"
author: "William Denney"
date: "October 21, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# General Remarks
The data specification in this section assumes an "NCA function" in R (or an R package) that calculates the PK parameters from one concentration-time profile (i.e., a series of time/concentration value pairs) that represent the sampled data for one subject after the administration of the study drug at time zero (for PO or IV bolus administration) or starting at time zero (for IV infusion administration). In addition, there are variables that contain subject or data specific characteristics or NCA options to be used when calculating the PK parameters. 

# Input Data: Analysis Data
These are the concentration-time profile and dosing data that are actually analyzed by the NCA function. Note that unit variables are not listed here as they are not actually used in the NCA calculations. 

* Observation/Sample inputs (the concentration measurement and time point vectors have to be of equal length):
    * Vector of observations (concentration and volume measurements):
        * the concentration value (are these already adjusted using applicable BQL rule? )
        * the volume value (for urine samples)
    * Vectors of time points for concentration measurements:
        * Nominal collection time or nominal start time of collection interval since first dose (really required??? Not needed or used for NCA, right?)
        * Nominal collection time or nominal start time of collection interval since the reference dose for the profile
        * Actual collection time or actual start time of collection interval since first dose (really required??? Not needed or used for NCA, right?)
        * Actual collection time or actual start time of collection interval since the reference dose for the profile
     * Vectors of time points indicating the end of a collection interval (for example, for urine studies)      
        * Nominal end time of collection interval since first dose (really required??? Not needed or used for NCA, right?)
        * Nominal end time of collection interval since the reference dose for the profile
        * Actual end time of collection interval since first dose (really required??? Not needed or used for NCA, right?)
        * Actual end time of collection interval since the reference dose for the profile
* Dosing inputs:
    * Dose definition:
        * The amount of the reference dose
        * Value to indicate the route of administration (e.g. "intravascular bolus", "intravascular infusion", or "extravascular") 
        * Flag to indicate single or multiple dose administration (really required??? I would expect that the "steady-state flag" is sufficient. 
        * Flag to indicate if steady-state has been achieved (only applicable for multiple dose administration)
    * Dose time inputs (all are zero for single-dose):
        * Nominal time point or nominal start time of reference dose (really required??? Not needed or used for NCA, right?)
        * Actual time point or actual start time of reference dose (should always be zero, right???)
        * Nominal duration of dose administration for intravascular infusion (not in ADNCA specification)
        * Actual duration of dose administration for intravascular infusion 
        * Time between dose administration for multiple dose administration (often referred to as TAU);

# Input Data: Characteristics
* Limit of Quantification
    * (Optional) the lower limit of quantification
    * (Optional) the upper limit of quantification
* Analyte
    * (Optional) flag that indicates that the analyte is a metabolite and not the parent drug. Value is "Y" if the analyte is a metabolite.

# Input Data: NCA Options
* (Optional) vector of exclusion flags. Value is "Y" if a concentration-time value pair is excluded
* (Optional, default needs to be determined ???) Value that indicates how to handle loq-values (i.e., what BQL rule should be applied)
* (Optional, default needs to be determined ???) Value that indicates how to handle pre-dose samples (i.e., what pre-dose rule should be applied)
* Partial AUC ranges (the vectors for the start and end values of the partial AUC ranges have to be of equal length)
    * (Optional) Vector of the start values for time ranges for partial AUC calculation (e.g., 0 and 12 for calculating AUC0-24 and AUC12-24);
    * (Optional) Vector of the end values for time ranges for partial AUC calculation (e.g., 24 and 24 for calculating AUC0-24 and AUC12-24);
* LambdaZ calculation (if no values are provided, the LambdaZ range is determined automatically by the NCA function
    * (Optional) start value of the range to be used for lz estimation;
    * (Optional) end value of the range to be used for lz estimation;


## CDISC Alignment 

The input data requirements represent a subset of a dataset as defined by the ADaM subteam working on ADaM NCA standard. 

The NCA Consortium Speficication does not require that input data should conform to the ADNCA standard (which is still under development) or the relevant SDTM PC and EX domain specifications for concentration and dosing data. However, it is recommended that analysis data should conform to the ADAM NCA standard as closely as feasible. When the ADAM ADNCA specification becomes standardized, this document should be revised to align with that standard. SDTM or ADaM column names are not required but are preferred, and any software should be anabled to use CDISC-formatted data by default. To support the use of other data standards the minimum specifications are provided above.

* ADNCA Specification
A file called "ADNCA_Variables_Draft_NCA-Consortium.xlsx" lists variables as defined in the current draft of the ADNCA specification with comments and how these variables could be derived from SDTM domains. 

# Output Data

Outputs should align with the SDTM PP domain. MORE NEEDS TO BE DEFINED ...
